name:                spl-compiler
version:             0.1.0.0
license:             BSD3
author:              "Orpheas van Rooij, Joshua Steinmann"
maintainer:          "orpheas.vanrooij@ru.nl"
copyright:           "2022 Orpheas van Rooij, Joshua Steinmann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A compiler for SPL (Simple Programming Language)
# category:            Compilers

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://gitlab.science.ru.nl/compilerconstruction/2122/group-14#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- extra
- array
- containers
- bytestring
- text
- mtl
- random
- MonadRandom
- HTF
- lens
- data-default
- optparse-applicative

library:
  source-dirs: src

executables:
  spl-compiler:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    # - -O2
    - -with-rtsopts=-N
    dependencies:
    - spl-compiler

tests:
  spl-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spl-compiler
 
